### ISSUE TITLE
crash with malformed command arguments

### ISSUE THREAD

**Issue by nolange** [fabrix/org.fabrix.activator#2]
Hello,

I am trying to evaluate varlink and ran into a segfault on the way.

```
./com.redhat.resolver --varlink=unix:/run/user/1000/org.varlink.resolver

./varlink call unix:/run/user/1000/org.varlink.resolver/com.redhat.resolver.AddServices '{ "services": [ { "address": "none", "intefaces" : [ "ia" ], "executable": "o"  } ] } '
```

```
#0  0x00007ffff7fc3164 in varlink_object_get_bool (object=0x0, field_name=0x555555559044 "activate_at_startup", bp=0x7fffffffdc7f)
    at ../../home/lano/git/libvarlink/lib/object.c:211
#1  0x000055555555779d in com_redhat_resolver_AddServices (resolver_service=<optimized out>, call=0x555555561da0, parameters=<optimized out>, flags=<optimized out>, 
    userdata=0x55555555d260) at ../../home/lano/git/com.redhat.resolver/src/main.c:397
#2  0x00007ffff7fc5709 in varlink_service_method_callback (service=0x55555555d340, call=0x555555561da0, parameters=<optimized out>, flags=<optimized out>, 
    userdata=<optimized out>) at ../../home/lano/git/libvarlink/lib/service.c:280
#3  0x00007ffff7fc4da1 in varlink_service_dispatch_connection (events=1, connection=0x555555561590, service=0x55555555d340)
    at ../../home/lano/git/libvarlink/lib/service.c:553
#4  varlink_service_process_events (service=0x55555555d340) at ../../home/lano/git/libvarlink/lib/service.c:602
#5  0x00005555555566b7 in main (argc=<optimized out>, argv=<optimized out>) at ../../home/lano/git/com.redhat.resolver/src/main.c:742

```

PS. is this repo actually alive, or is the go implementation your working reference?

**Comment by nolange** [comment]
Also, there seems to be heap corruptions in other cases. Leading to immediate crashes, or crashes later on.
```
./varlink call unix:/run/user/1000/org.varlink.resolver/com.redhat.resolver.AddServices '{ "services": [ { "address": "none", "interfaces" : [ "ia" ], "executable": { "path": "o" } } ] } '
```


```
==5999== Memcheck, a memory error detector
==5999== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==5999== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==5999== Command: ./com.redhat.resolver --varlink=unix:/run/user/1000/org.varlink.resolver
==5999== 
==5999== Invalid read of size 8
==5999==    at 0x4847226: varlink_array_unref (array.c:104)
==5999==    by 0x4849C16: field_freep (object.c:33)
==5999==    by 0x4847E33: avl_tree_free_subtree (avltree.c:180)
==5999==    by 0x4847E25: avl_tree_free_subtree (avltree.c:177)
==5999==    by 0x4847F2B: avl_tree_free (avltree.c:186)
==5999==    by 0x4849D9D: varlink_object_unref (object.c:165)
==5999==    by 0x10B84B: com_redhat_resolver_AddServices (main.c:363)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Address 0x4a7d940 is 0 bytes inside a block of size 48 free'd
==5999==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x484726D: varlink_array_unref (array.c:111)
==5999==    by 0x10B835: com_redhat_resolver_AddServices (main.c:365)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Block was alloc'd at
==5999==    at 0x4837B65: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x48472B7: varlink_array_new (array.c:38)
==5999==    by 0x4847328: varlink_array_new_from_scanner (array.c:56)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x48473B0: varlink_array_new_from_scanner (array.c:75)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484A075: varlink_object_new_from_json (object.c:143)
==5999== 
==5999== Invalid write of size 8
==5999==    at 0x484722D: varlink_array_unref (array.c:104)
==5999==    by 0x4849C16: field_freep (object.c:33)
==5999==    by 0x4847E33: avl_tree_free_subtree (avltree.c:180)
==5999==    by 0x4847E25: avl_tree_free_subtree (avltree.c:177)
==5999==    by 0x4847F2B: avl_tree_free (avltree.c:186)
==5999==    by 0x4849D9D: varlink_object_unref (object.c:165)
==5999==    by 0x10B84B: com_redhat_resolver_AddServices (main.c:363)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Address 0x4a7d940 is 0 bytes inside a block of size 48 free'd
==5999==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x484726D: varlink_array_unref (array.c:111)
==5999==    by 0x10B835: com_redhat_resolver_AddServices (main.c:365)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Block was alloc'd at
==5999==    at 0x4837B65: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x48472B7: varlink_array_new (array.c:38)
==5999==    by 0x4847328: varlink_array_new_from_scanner (array.c:56)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x48473B0: varlink_array_new_from_scanner (array.c:75)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484A075: varlink_object_new_from_json (object.c:143)
==5999== 
==5999== Invalid read of size 8
==5999==    at 0x4849D80: varlink_object_unref (object.c:162)
==5999==    by 0x4849C16: field_freep (object.c:33)
==5999==    by 0x4847E33: avl_tree_free_subtree (avltree.c:180)
==5999==    by 0x4847F2B: avl_tree_free (avltree.c:186)
==5999==    by 0x4849D9D: varlink_object_unref (object.c:165)
==5999==    by 0x10B84B: com_redhat_resolver_AddServices (main.c:363)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Address 0x4a76ce0 is 0 bytes inside a block of size 24 free'd
==5999==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x4849DA6: varlink_object_unref (object.c:166)
==5999==    by 0x10B840: com_redhat_resolver_AddServices (main.c:364)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Block was alloc'd at
==5999==    at 0x4837B65: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x4849DE7: varlink_object_new (object.c:67)
==5999==    by 0x4849EA5: varlink_object_new_from_scanner (object.c:91)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x48473B0: varlink_array_new_from_scanner (array.c:75)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484A075: varlink_object_new_from_json (object.c:143)
==5999== 
==5999== Invalid read of size 8
==5999==    at 0x4849D80: varlink_object_unref (object.c:162)
==5999==    by 0x4847254: varlink_array_unref (array.c:108)
==5999==    by 0x10B85E: com_redhat_resolver_AddServices (main.c:351)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Address 0x4a70080 is 0 bytes inside a block of size 24 free'd
==5999==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x4849DA6: varlink_object_unref (object.c:166)
==5999==    by 0x10B84B: com_redhat_resolver_AddServices (main.c:363)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Block was alloc'd at
==5999==    at 0x4837B65: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x4849DE7: varlink_object_new (object.c:67)
==5999==    by 0x4849EA5: varlink_object_new_from_scanner (object.c:91)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x48473B0: varlink_array_new_from_scanner (array.c:75)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484A075: varlink_object_new_from_json (object.c:143)
==5999==    by 0x484CAA1: varlink_stream_read (stream.c:100)
==5999==    by 0x484BDD2: varlink_service_dispatch_connection (service.c:541)
==5999==    by 0x484BDD2: varlink_service_process_events (service.c:602)
==5999== 
==5999== Invalid read of size 8
==5999==    at 0x4847226: varlink_array_unref (array.c:104)
==5999==    by 0x4849C16: field_freep (object.c:33)
==5999==    by 0x4847E33: avl_tree_free_subtree (avltree.c:180)
==5999==    by 0x4847F2B: avl_tree_free (avltree.c:186)
==5999==    by 0x4849D9D: varlink_object_unref (object.c:165)
==5999==    by 0x4849C16: field_freep (object.c:33)
==5999==    by 0x4847E33: avl_tree_free_subtree (avltree.c:180)
==5999==    by 0x4847E25: avl_tree_free_subtree (avltree.c:177)
==5999==    by 0x4847F2B: avl_tree_free (avltree.c:186)
==5999==    by 0x4849D9D: varlink_object_unref (object.c:165)
==5999==    by 0x484BE46: varlink_service_dispatch_connection (service.c:539)
==5999==    by 0x484BE46: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Address 0x4a6fed0 is 0 bytes inside a block of size 48 free'd
==5999==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x484726D: varlink_array_unref (array.c:111)
==5999==    by 0x10B85E: com_redhat_resolver_AddServices (main.c:351)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Block was alloc'd at
==5999==    at 0x4837B65: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x48472B7: varlink_array_new (array.c:38)
==5999==    by 0x4847328: varlink_array_new_from_scanner (array.c:56)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484A075: varlink_object_new_from_json (object.c:143)
==5999==    by 0x484CAA1: varlink_stream_read (stream.c:100)
==5999==    by 0x484BDD2: varlink_service_dispatch_connection (service.c:541)
==5999==    by 0x484BDD2: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999== 
==5999== Invalid write of size 8
==5999==    at 0x484722D: varlink_array_unref (array.c:104)
==5999==    by 0x4849C16: field_freep (object.c:33)
==5999==    by 0x4847E33: avl_tree_free_subtree (avltree.c:180)
==5999==    by 0x4847F2B: avl_tree_free (avltree.c:186)
==5999==    by 0x4849D9D: varlink_object_unref (object.c:165)
==5999==    by 0x4849C16: field_freep (object.c:33)
==5999==    by 0x4847E33: avl_tree_free_subtree (avltree.c:180)
==5999==    by 0x4847E25: avl_tree_free_subtree (avltree.c:177)
==5999==    by 0x4847F2B: avl_tree_free (avltree.c:186)
==5999==    by 0x4849D9D: varlink_object_unref (object.c:165)
==5999==    by 0x484BE46: varlink_service_dispatch_connection (service.c:539)
==5999==    by 0x484BE46: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Address 0x4a6fed0 is 0 bytes inside a block of size 48 free'd
==5999==    at 0x48369AB: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x484726D: varlink_array_unref (array.c:111)
==5999==    by 0x10B85E: com_redhat_resolver_AddServices (main.c:351)
==5999==    by 0x484C708: varlink_service_method_callback (service.c:280)
==5999==    by 0x484BDA0: varlink_service_dispatch_connection (service.c:553)
==5999==    by 0x484BDA0: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999==  Block was alloc'd at
==5999==    at 0x4837B65: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==5999==    by 0x48472B7: varlink_array_new (array.c:38)
==5999==    by 0x4847328: varlink_array_new_from_scanner (array.c:56)
==5999==    by 0x484EB6C: varlink_value_read_from_scanner (value.c:49)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484EB94: varlink_value_read_from_scanner (value.c:42)
==5999==    by 0x4849F6A: varlink_object_new_from_scanner (object.c:115)
==5999==    by 0x484A075: varlink_object_new_from_json (object.c:143)
==5999==    by 0x484CAA1: varlink_stream_read (stream.c:100)
==5999==    by 0x484BDD2: varlink_service_dispatch_connection (service.c:541)
==5999==    by 0x484BDD2: varlink_service_process_events (service.c:602)
==5999==    by 0x10A6B6: main (main.c:742)
==5999== 
```

**Comment by nolange** [comment]
Well, I fixed it myself. For reference:

```patch
fix heap allocations and deallocations

---
 src/main.c    | 8 ++++----
 src/service.c | 4 ++--
 2 files changed, 6 insertions(+), 6 deletions(-)

diff --git a/src/main.c b/src/main.c
index 3eeee20..530150b 100644
--- a/src/main.c
+++ b/src/main.c
@@ -348,7 +348,7 @@ static long com_redhat_resolver_AddServices(VarlinkService *resolver_service,
                                               void *userdata) {
         Manager *m = userdata;
         long n_services;
-        _cleanup_(varlink_array_unrefp) VarlinkArray *servicesv = NULL;
+        VarlinkArray *servicesv = NULL;
         long r;
 
         r = varlink_object_get_array(parameters, "services", &servicesv);
@@ -360,9 +360,9 @@ static long com_redhat_resolver_AddServices(VarlinkService *resolver_service,
                 return n_services;
 
         for (long s = 0; s < n_services; s += 1) {
-                _cleanup_(varlink_object_unrefp) VarlinkObject *servicev = NULL;
-                _cleanup_(varlink_object_unrefp) VarlinkObject *executablev = NULL;
-                _cleanup_(varlink_array_unrefp) VarlinkArray *interfacesv = NULL;
+                VarlinkObject *servicev = NULL;
+                VarlinkObject *executablev = NULL;
+                VarlinkArray *interfacesv = NULL;
                 const char *address;
                 const char *executable = NULL;
                 uid_t uid = (uid_t)-1;
diff --git a/src/service.c b/src/service.c
index 2978c0f..e8a38ef 100644
--- a/src/service.c
+++ b/src/service.c
@@ -94,8 +94,8 @@ Service *service_free(Service *service) {
                 free(service->interfaces[i]);
         free(service->interfaces);
 
-        for (char *arg = *service->argv; arg ; arg++)
-                free(arg);
+        for (char **arg = service->argv; *arg ; arg++)
+                free(*arg);
         free(service->argv);
 
         free(service->address);
-- 
2.20.1
```



```patch
fix wrong access of executable fields

this can led to segfaults
---
 src/main.c | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/main.c b/src/main.c
index 530150b..bb3d961 100644
--- a/src/main.c
+++ b/src/main.c
@@ -387,14 +387,14 @@ static long com_redhat_resolver_AddServices(VarlinkService *resolver_service,
                         if (r < 0)
                                 return r;
 
-                        if (varlink_object_get_int(servicev, "user_id", &i) >= 0)
+                        if (varlink_object_get_int(executablev, "user_id", &i) >= 0)
                                 uid = i;
 
-                        if (varlink_object_get_int(servicev, "group_id", &i) >= 0)
+                        if (varlink_object_get_int(executablev, "group_id", &i) >= 0)
                                 gid = i;
                 }
 
-                varlink_object_get_bool(executablev, "activate_at_startup", &activate);
+                varlink_object_get_bool(servicev, "activate_at_startup", &activate);
 
                 r = varlink_object_get_array(servicev, "interfaces", &interfacesv);
                 if (r < 0)
-- 
2.20.1
```
